-- 코드를 입력하세요
SELECT 
    H.HISTORY_ID,
    C.DAILY_FEE * 
    (100 - COALESCE(P.DISCOUNT_RATE, 0)) / 100 *
    (DATEDIFF(H.END_DATE, H.START_DATE) + 1) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
    AND (
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 AND P.DURATION_TYPE = 90)
        OR
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 AND P.DURATION_TYPE = 30)
        OR
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 AND P.DURATION_TYPE = 7)
    )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;